export { MovieNowPlaying } from './MovieNowPlaying'
export { MoviePopular } from './MoviePopular'
export { MovieDetail } from './MovieDetail'
export { Trending } from './Trending'
export { TvTopRated } from './TvTopRated'
export { TvPopular } from './TvPopular'
export { TvDetail } from './TvDetail'